### ISSUE TITLE
Знайти фото Нового Роздолу в Інтернеті

### ISSUE THREAD

**Issue by nrpk3** [nrpk3/pr4_2020#1]
Знайти найкраще фото в Інтернеті

**Comment by nrpk2** [comment]
Вже шукаю

**Comment by nrpk2** [comment]
https://varianty.lviv.ua/thumbnails/640x360/cb88cfdfe163d542eb7cf22092b59d03.jpg

**Comment by nrpk2** [comment]
![image](https://user-images.githubusercontent.com/5570074/98471086-a214b380-21f2-11eb-8406-71d8e4d16a9a.png)

**Comment by nrpk2** [comment]
Зображення знайдено
